# Generated by Django 5.2.7 on 2025-11-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="venues",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venues",
            name="cover_image",
            field=models.ImageField(blank=True, upload_to="venues"),
        ),
        migrations.AddField(
            model_name="venues",
            name="facebook_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="venues",
            name="google_map_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="venues",
            name="instagram_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="venues",
            name="logo",
            field=models.ImageField(blank=True, upload_to="venues"),
        ),
        migrations.AddField(
            model_name="venues",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="venues",
            name="website_url",
            field=models.URLField(blank=True),
        ),
    ]
