# Generated by Django 5.2.7 on 2025-11-08 13:59

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("venues", "0002_venues_closing_time_venues_cover_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SlotConfigurationn",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                (
                    "duration",
                    models.DurationField(default=datetime.timedelta(seconds=3600)),
                ),
                ("base_price_hour", models.FloatField()),
                ("weekend_price_hour", models.FloatField(blank=True, null=True)),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="venues.venues"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
                ("price", models.FloatField()),
                (
                    "status",
                    models.CharField(
                        choices=[("AVAILABLE", "Available"), ("BOOKED", "Booked")],
                        default="AVAILABLE",
                        max_length=50,
                    ),
                ),
                (
                    "slot_condiguartion",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="venues.slotconfigurationn",
                    ),
                ),
                (
                    "venue",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="venues.venues"
                    ),
                ),
            ],
        ),
    ]
